/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmsys.gui;
import bmsys.po.Employee;
import bmsys.dao.Employeedao;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author राधे~राधे !
 */
public class EmployeeCreateAccount extends javax.swing.JFrame {
String gender;
    /**
     * Creates new form CustomerCreateAccount
     */
    public EmployeeCreateAccount() {
        initComponents();
        connect();
        ClearAllField();
    }
    public void connect(){
    for(int i=0;i<=115;i++)
    {
      jComboBox1.addItem(String.valueOf(i));
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MaleRB = new javax.swing.JRadioButton();
        FemaleRB = new javax.swing.JRadioButton();
        OtherRB = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1530, 1000));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 0, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Employee Account");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1520, 120);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 150, 360, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date of Birth ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 240, 150, 25);

        jDateChooser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jDateChooser1.setToolTipText("");
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(280, 230, 200, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email ID ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 440, 110, 40);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(270, 440, 330, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 360, 90, 30);

        MaleRB.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        MaleRB.setForeground(new java.awt.Color(255, 255, 255));
        MaleRB.setText("Male");
        MaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRBActionPerformed(evt);
            }
        });
        getContentPane().add(MaleRB);
        MaleRB.setBounds(270, 370, 71, 33);

        FemaleRB.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        FemaleRB.setForeground(new java.awt.Color(255, 255, 255));
        FemaleRB.setText("Female");
        FemaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRBActionPerformed(evt);
            }
        });
        getContentPane().add(FemaleRB);
        FemaleRB.setBounds(370, 370, 89, 33);

        OtherRB.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        OtherRB.setForeground(new java.awt.Color(255, 255, 255));
        OtherRB.setText("Other");
        OtherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherRBActionPerformed(evt);
            }
        });
        getContentPane().add(OtherRB);
        OtherRB.setBounds(500, 370, 79, 33);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1120, 530, 320, 116);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(1120, 660, 320, 116);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Present Address");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(920, 570, 160, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Permanent Address");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(900, 700, 190, 40);

        jCheckBox1.setForeground(new java.awt.Color(51, 51, 0));
        jCheckBox1.setText("Present Address same as permanent address");
        jCheckBox1.setEnabled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(1120, 790, 289, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adhar No");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(920, 310, 110, 25);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 153));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(270, 500, 280, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 310, 90, 30);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jComboBox1.setToolTipText("");
        jComboBox1.setAutoscrolls(true);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 300, 130, 31);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Cashier", "Cleark" }));
        jComboBox2.setToolTipText("");
        jComboBox2.setAutoscrolls(true);
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(1120, 160, 130, 31);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Position");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(920, 160, 130, 30);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(1120, 220, 300, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PAN No");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(920, 230, 120, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact No");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 520, 120, 25);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 153));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(1120, 300, 310, 40);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("User ID");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 590, 130, 25);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(270, 580, 280, 40);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Confirm Password");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(60, 740, 180, 30);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(270, 740, 280, 40);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 660, 110, 30);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(270, 660, 280, 40);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Employee Name");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 160, 210, 25);

        BackButton.setFont(new java.awt.Font("Script MT Bold", 1, 30)); // NOI18N
        BackButton.setForeground(new java.awt.Color(102, 0, 51));
        BackButton.setText("<<");
        BackButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(20, 880, 130, 50);

        jButton1.setFont(new java.awt.Font("Script MT Bold", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 51));
        jButton1.setText("Create");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 830, 150, 60);

        jButton2.setFont(new java.awt.Font("Script MT Bold", 1, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 51));
        jButton2.setText("Clear");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(860, 830, 150, 60);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Country");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(920, 450, 110, 30);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(1120, 450, 260, 40);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("State");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(920, 370, 110, 30);

        jTextField11.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(1120, 370, 260, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/createAcc.jpeg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1520, 1000));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 110, 1520, 880);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        //Only Allow Letter
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            jTextField1.setEditable(true);
        }
        else
        {
            jTextField1.setEditable(false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void MaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRBActionPerformed
        // TODO add your handling code here:
        if(MaleRB.isSelected())
        {
            gender = MaleRB.getText();
            FemaleRB.setSelected(false);
            OtherRB.setSelected(false);
        }
    }//GEN-LAST:event_MaleRBActionPerformed

    private void FemaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRBActionPerformed
        // TODO add your handling code here:
        if(FemaleRB.isSelected())
        {
            gender = FemaleRB.getText();
            MaleRB.setSelected(false);
            OtherRB.setSelected(false);
        }
    }//GEN-LAST:event_FemaleRBActionPerformed

    private void OtherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherRBActionPerformed
        // TODO add your handling code here:
        if(OtherRB.isSelected())
        {
            gender = OtherRB.getText();
            FemaleRB.setSelected(false);
            MaleRB.setSelected(false);
        }
    }//GEN-LAST:event_OtherRBActionPerformed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // TODO add your handling code here:
        jCheckBox1.setEnabled(true);
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            jTextArea2.setText(jTextArea1.getText());
        }
        else
        {
            jTextArea2.setText("");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        //Only Allow Digit PhoneNumber length 10
        char c=evt.getKeyChar();
        String no=jTextField5.getText();
        int len=no.length();
        if(Character.isDigit(c))
        {
            if(len<10)
            {
                jTextField5.setEditable(true);
            }
            else
            {
                jTextField5.setEditable(false);
            }
        }else
        {
            if(Character.isWhitespace(c)||Character.isISOControl(c))
            jTextField5.setEditable(true);
            else
            jTextField5.setEditable(false);
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String no=jTextField3.getText();
        if(Character.isDigit(c)||Character.isUpperCase(c))
        {
            if(no.length()<10)
            {
                jTextField3.setEditable(true);
            }
            else
                jTextField3.setEditable(false);
        }
        else
        {
            if(Character.isWhitespace(c)||Character.isISOControl(c))
            jTextField3.setEditable(true);
            else
            jTextField3.setEditable(false);
        }   
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        //Only Allow Digit Adhar Number length 16
        char c=evt.getKeyChar();
        String no=jTextField6.getText();
        int len=no.length();
        if(Character.isDigit(c))
        {
            if(len<12)
            {
                jTextField6.setEditable(true);
            }
            else
            {
                jTextField6.setEditable(false);
            }
        }else
        {
            if(Character.isWhitespace(c)||Character.isISOControl(c))
            jTextField6.setEditable(true);
            else
            jTextField6.setEditable(false);
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9KeyPressed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
       new EmployeeLogin().show();
       this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 try
        {
        Employee u=new Employee();
        u.setEmployeeName(jTextField1.getText());
        u.setDob(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
        u.setAge(jComboBox1.getSelectedItem().toString());
        u.setGender(gender);
        u.setEmail(jTextField7.getText());
        u.setContactno(jTextField5.getText());
        u.setUserId(jTextField4.getText());
        u.setPassword(jTextField9.getText());
        u.setConfirmPassword(jTextField8.getText());
        u.setState(jTextField11.getText());
        u.setCountry(jTextField10.getText());
        u.setPosition(jComboBox2.getSelectedItem().toString());
        u.setPanNo(jTextField3.getText());
        u.setAdharNo(jTextField6.getText());
        u.setPerAddress(jTextArea1.getText());
        u.setTempAddress(jTextArea2.getText());

        boolean vi= validateInput(u); 
       if(vi!=true)
       {
         JOptionPane.showMessageDialog(this,"Some Field is Empty","Empty Text",JOptionPane.ERROR_MESSAGE);
        }
       else
       {
        if(Employeedao.isValidUserId(u)==true)
        {
             if(u.getConfirmPassword().equals(u.getPassword()))
             {
                if(Employeedao.isValidEmail(u.getEmail())==true)
                {
                    if(Employeedao.isValidPanNo(u.getPanNo())==true)
                    {
                        if(Employeedao.isValidContactNo(u.getContactno())==true)
                        {
                            if(u.getAdharNo().length()==12)
                            {
                                Employeedao.CreateEmployee(u);
                                JOptionPane.showMessageDialog(null,"Customer Create Succesfully","Record Insert",JOptionPane.INFORMATION_MESSAGE);
                                ClearAllField();
                            }
                            else
                                JOptionPane.showMessageDialog(null,"Please Enter Valide Adhar No","Error ",JOptionPane.ERROR_MESSAGE);
                        }
                        else
                            JOptionPane.showMessageDialog(null,"Please Provide Valid Contact No","Error ",JOptionPane.ERROR_MESSAGE);
                    }
                    else
                        JOptionPane.showMessageDialog(null,"Please Enter Valid PAN no","Error ",JOptionPane.ERROR_MESSAGE);
                }    
                else
                    JOptionPane.showMessageDialog(null,"Please Enter Valid Email Id","Error ",JOptionPane.ERROR_MESSAGE);
            }
             else
                JOptionPane.showMessageDialog(null,"Password and Confirm Password not Match","Error ",JOptionPane.ERROR_MESSAGE);
       }
       else
        JOptionPane.showMessageDialog(null,"User Id Already Present..","Error ",JOptionPane.ERROR_MESSAGE);
    }
   }
    catch(NullPointerException e)
    {
        JOptionPane.showMessageDialog(null,"Some Field are Empty","Exception ",JOptionPane.ERROR_MESSAGE);
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e+"","Exception ",JOptionPane.ERROR_MESSAGE);
    }
       
    }//GEN-LAST:event_jButton1ActionPerformed
private boolean validateInput(Employee u)
{
    if(u.getEmployeeName().isEmpty()||u.getAge().isEmpty()||u.getAdharNo().isEmpty()||u.getPosition().isEmpty()||u.getContactno().isEmpty()||u.getDob().isEmpty()||u.getPanNo().isEmpty()||u.getPerAddress().isEmpty()||u.getTempAddress().isEmpty()||u.getUserId().isEmpty()||u.getConfirmPassword().isEmpty())
  {
    return false;
  }
  else
  {
    return true;
  }
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ClearAllField();
    }//GEN-LAST:event_jButton2ActionPerformed
public void ClearAllField()
{
        jComboBox1.setSelectedItem(null);
        jComboBox2.setSelectedItem(null);
        jDateChooser1.setDate(null);
        jTextField1.setText("");
        //jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextArea1.setText("");
        jTextArea2.setText("");
        MaleRB.setSelected(false);
        FemaleRB.setSelected(false);
        OtherRB.setSelected(false);
        jCheckBox1.setSelected(false);
        jCheckBox1.setEnabled(false);
  
}
    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeCreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton FemaleRB;
    private javax.swing.JRadioButton MaleRB;
    private javax.swing.JRadioButton OtherRB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
